title: COVID-19 evolution 
author: Serge Dudnic

description: > 
  The site about COVID-19 evolution, 
  graphs and API's used to show the new virus
  propagation, cases, recoveries, deaths etc.

theme: jekyll-theme-cayman

# social links
twitter_username: sdudnic
github_username:  sdudnic
facebook_username: serge.dudnic

show_excerpts: true # set to false to remove excerpts on the homepage
